pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode {
        PREFER_SETTINGS()
        FAIL_ON_PROJECT_REPOS()
    }
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "glass-swing"
include(":app")
